# Generated by Django 5.1.2 on 2024-12-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumar', '0005_emailrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person giving feedback', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the person giving feedback', max_length=254)),
                ('feedback', models.TextField(help_text='Feedback message provided by the user')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the feedback was submitted')),
            ],
        ),
    ]
